<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="sudoku_logic_tests.Sudoku_logic_test-20211206112101" tests="1" file="sudoku_logic_tests.py" time="0.003" timestamp="2021-12-06T11:21:01" failures="0" errors="1" skipped="0">
	<testcase classname="sudoku_logic_tests.Sudoku_logic_test" name="test" time="0.003" timestamp="2021-12-06T11:21:01">
		<error type="AttributeError" message="'bool' object has no attribute 'all'"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/flora/PycharmProjects/SudokuGame/src/unittest/python/sudoku_logic_tests.py", line 7, in test
    self.assertTrue(True.all())
AttributeError: 'bool' object has no attribute 'all'
]]></error>
	</testcase>
</testsuite>
